config/routes.rb
Tripping::Application.routes.draw do
    
  resources :photosets, :only => [:index, :show] do
    member do
      get 'slideshow'
    end
  end

  namespace :admin do
    resources :photosets, :only => [:create, :destroy, :update] do
      collection do
        post 'save_order'
      end
    end
  end

  
  root :to => "pages#home"

  match "/admin/" => "admin#index", :as => :admin
  match "/friends/" => "photosets#friends"
  match "/about/" => "pages#about"
  match "/proxy/" => "pages#image_proxy"
end

app/models/photoset.rb
# == Schema Information
#
# Table name: photosets
#
#  id               :integer         not null, primary key
#  name             :string(255)
#  flickr_set_id    :integer
#  created_at       :datetime
#  updated_at       :datetime
#  flickr_thumb_url :string(255)
#  position         :integer
#

class Photoset < ActiveRecord::Base
	has_many :photo, :dependent => :destroy
	
	default_scope :order => 'position'

	def to_param
		"#{id} #{name}".parameterize
	end

	def self.refresh_order
		self.all.each_with_index do |photoset, index|
			photoset.update_attributes(:position => index + 1)
		end
	end
	
end

app/controllers/admin/photosets_controller.rb
class Admin::PhotosetsController < ApplicationController

  http_basic_authenticate_with :name => Tripping::Application.config.admin_username,
                   :password => Tripping::Application.config.admin_password

  before_filter :flickr_authenticate, :only => [:create, :update]

 def create
    new_photoset = Photoset.new(params[:photoset])
    flickr_photos = photos_flickr_params(params[:photoset][:flickr_set_id])
    new_photoset.photo.build(flickr_photos)
    if new_photoset.save!
      Photoset.refresh_order
      flash[:Success] = 'Photoset imported.'
      redirect_to admin_path
    else
      flash[:error] = 'Something went wrong.'
      redirect_to admin_path
    end
  end
  
  def destroy
    photoset = Photoset.find(params[:id])
    if photoset.destroy
      Photoset.refresh_order
      flash[:success] = "Photoset deleted."
    else
      flash[:error] = "I couldn't delete the photoset. Don't know why."
    end
  	redirect_to admin_path
  end

  def update
    @photoset = Photoset.find(params[:id])
    thumbs = update_thumbs(@photoset)
    photos = update_photos(@photoset)
    if thumbs && photos
      flash[:success] = "Photoset " + @photoset.name + " updated."
    end
    redirect_to admin_path
  end

  def save_order
    params[:set].each_with_index do |id, index|
      Photoset.update_all({position: index+1}, {id: id})
    end
    render nothing: true
  end

  private

  def update_thumbs(photoset) 
    flickr_set = flickr_set(photoset.flickr_set_id)
    photoset.flickr_thumb_url = flickrurl_240(flickr_set.primary)
    photoset.save!
  end

  def update_photos(photoset)
    flickr_photos = photos_flickr_params(photoset.flickr_set_id)

    flickr_photos.each_with_index do |flickr_photo, index| #updates and new photos
      flickr_photo[:position] = index
      photo = photoset.photo.find_by_flickr_photo_id(flickr_photo[:flickr_photo_id])
      if photo
        photo.update_attributes(flickr_photo)
      else
        photoset.photo.build(flickr_photo)
      end
    end

    if photoset.photo.count > flickr_photos.length #handle deletion
      photoset.photo.each do |photo|
        photo.destroy unless flickr_photos.any? {|p| p[:flickr_photo_id] == photo.flickr_photo_id}
      end
    end
    photoset.save!
  end

end

app/controllers/photosets_controller.rb
class PhotosetsController < ApplicationController

  def index
    redirect_to root_path
  end

  def show
    @title = Photoset.find(params[:id]).name
    if session[:friends]
      @photos = Photoset.find(params[:id]).photo.paginate(:page => params[:page], :per_page => 20)
    else
      @photos = Photoset.find(params[:id]).photo.only_public.paginate(:page => params[:page], :per_page => 20)
    end
  end

  def slideshow
    @photoset = Photoset.find(params[:id])
    @title = "Slideshow: " + @photoset.name
    if session[:friends]
      @photos = Photoset.find(params[:id]).photo.all
    else
      @photos = Photoset.find(params[:id]).photo.only_public.all
    end
  end

  def friends
    session[:friends] = true
    redirect_to root_path
  end
end

app/helpers/photosets_helper.rb
module PhotosetsHelper
end

app/views/photosets/_photo.html.erb
<div class="photo"><%= image_tag photo.url %></div>

app/views/photosets/_photo_slideshow.html.erb
{image : '<%= photo_slideshow.url %>', title : '<%= @photoset.name %>', thumb : '<%= photo_slideshow.thumb_url %>'},

app/views/photosets/_share_panel.bkp.html.erb
<div id="share_panel_top">
<div class="fb-like fb_edge_widget_with_comment fb_iframe_widget" data-send="false" data-layout="box_count" data-width="55" data-show-faces="false"><span><iframe id="f3811592fc" name="f2f8a4ea" scrolling="no" style="border-width: initial; border-color: initial; overflow-x: hidden; overflow-y: hidden; border-width: initial; border-color: initial; border-width: initial; border-color: initial; height: 62px; width: 55px; border-top-style: none; border-right-style: none; border-bottom-style: none; border-left-style: none; border-width: initial; border-color: initial; border-image: initial; " title="Like this content on Facebook." class="fb_ltr" src="http://www.facebook.com/plugins/like.php?api_key=183442523144&amp;channel_url=https%3A%2F%2Fs-static.ak.fbcdn.net%2Fconnect%2Fxd_proxy.php%3Fversion%3D3%23cb%3Df172167acc%26origin%3Dhttp%253A%252F%252Fwww.fotopedia.com%252Ff29c6667d%26relation%3Dparent.parent%26transport%3Dpostmessage&amp;extended_social_context=false&amp;href=http%3A%2F%2Fwww.fotopedia.com%2Fwiki%2FSingapore%23!%2Fitems%2Fd6buq3p8ercku-eBi4cxKwK-E&amp;layout=box_count&amp;locale=en_US&amp;node_type=link&amp;sdk=joey&amp;send=false&amp;show_faces=false&amp;width=55"></iframe></span></div>  
<div class="twitter-share-button-container"> 
<iframe allowtransparency="true" frameborder="0" scrolling="no" src="http://platform.twitter.com/widgets/tweet_button.html#_=1323976096392&amp;_version=2&amp;count=vertical&amp;enableNewSizing=false&amp;id=twitter-widget-0&amp;lang=en&amp;original_referer=http%3A%2F%2Fwww.fotopedia.com%2Fwiki%2FSingapore%23!%2Fitems%2Fd6buq3p8ercku-eBi4cxKwK-E&amp;related=fotopediamag&amp;size=m&amp;text=Singapore%20on%20Fotopedia&amp;url=http%3A%2F%2Fwww.fotopedia.com%2Fwiki%2FSingapore%23!%2Fitems%2Fd6buq3p8ercku-eBi4cxKwK-E&amp;via=fotopedia" class="twitter-share-button twitter-count-vertical" style="height: 62px; width: 55px; " title="Twitter Tweet Button"></iframe>
</div>
<div class="gplus-container"><div id="___plusone_0" style="height: 60px; width: 50px; display: inline-block; text-indent: 0px; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; background-image: initial; background-attachment: initial; background-origin: initial; background-clip: initial; background-color: transparent; border-top-style: none; border-right-style: none; border-bottom-style: none; border-left-style: none; float: none; line-height: normal; font-size: 1px; vertical-align: baseline; background-position: initial initial; background-repeat: initial initial; "><iframe allowtransparency="true" frameborder="0" hspace="0" id="I1_1323976096609" marginheight="0" marginwidth="0" name="I1_1323976096609" scrolling="no" src="https://plusone.google.com/_/+1/fastbutton?url=http%3A%2F%2Fwww.fotopedia.com%2Fwiki%2FSingapore%23!%2Fitems%2Fd6buq3p8ercku-eBi4cxKwK-E&amp;size=tall&amp;count=true&amp;annotation=&amp;hl=en-US&amp;jsh=m%3B%2F_%2Fapps-static%2F_%2Fjs%2Fwidget%2F__features__%2Frt%3Dj%2Fver%3De0Li34XqTDA.en_GB.%2Fsv%3D1%2Fam%3D!xVi4pEKcg86Ivi6-JA%2Fd%3D1%2F#id=I1_1323976096609&amp;parent=http%3A%2F%2Fwww.fotopedia.com&amp;rpctoken=377012525&amp;_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe" style="width: 50px; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; border-top-style: none; border-right-style: none; border-bottom-style: none; border-left-style: none; height: 60px; position: static; left: 0px; top: 0px; visibility: visible; " tabindex="-1" vspace="0" width="100%" title="+1"></iframe></div></div>
</div>
<div id="share_panel_bottom"></div>

app/views/photosets/_share_panel.html.erb
<div id="fb-root"></div>
<div id="share_panel_top">
<div class="fb-like fb_edge_widget_with_comment fb_iframe_widget"><fb:like send="false" layout="box_count" width="55" show_faces="false" font="arial"></fb:like></div>  
<div class="twitter-share-button-container"> 
<a href="https://twitter.com/share" class="twitter-share-button" data-lang="en" data-count="vertical" data-text="<%= @title %> by Tripping">Tweet</a>
</div>
<div class="gplus-container"><g:plusone size="tall"></g:plusone></div>
</div>
<div id="share_panel_bottom"></div>

app/views/photosets/show.html.erb
<% content_for :body_class, '' %>
<% content_for :header do %>
  <script type="text/javascript">
    $(document).ready(function() {
      /*
      var defaults = {
          containerID: 'moccaUItoTop', // fading element id
        containerHoverClass: 'moccaUIhover', // fading element hover class
        scrollSpeed: 1200,
        easingType: 'linear' 
      };
      */
      
      $().UItoTop({ easingType: 'easeOutQuart' });
      
    });
  </script>
<% end %>

<%= render 'shared/header' %>
<div id="photos_container">
	<div id="photos_header">
	    <h2><%= @title %></h2>
      <ul id="photos_menu">
        <li>
          <a href="" class="share_icons">Share</a>
          <div id="share_panel"><%= render :partial => 'share_panel'%></div>
        </li>
        <li>
          <%= link_to "Slideshow", slideshow_photoset_path(params[:id]), :class=> "slideshow_link" %>
        </li>
      </ul>
	</div>
	<%= render :partial => 'photo', :collection => @photos %>
</div>
<%= will_paginate @photos %>

<script>
  $('#photos_container').infinitescroll({
 
    navSelector  : "div.pagination",            
                   // selector for the paged navigation (it will be hidden)
    nextSelector : "div.pagination a.next_page",    
                   // selector for the NEXT link (to page 2)
    itemSelector : "#photos_container div.photo",          
                   // selector for all items you'll retrieve
    loadingText  : "Hang on, loading more photos...",      
                 // text accompanying loading image
                 // default: "<em>Loading the next set of posts...</em>"
    loadingImg   : "/images/supersized/progress.gif",          
                 // loading image.
                 // default: "http://www.infinite-scroll.com/loading.gif"
    donetext     : "I think we've hit the end, Jim"
                 // text displayed when all items have been retrieved
                 // default: "<em>Congratulations, you've reached the end of the internet.</em>"
  });
</script>

app/views/photosets/slideshow.html.erb
<% content_for :header do %>
    <%= stylesheet_link_tag 'supersized.tripping.css', :media => "screen" %>
    <%= stylesheet_link_tag 'supersized.shutter.css', :media => "screen" %>
	<%= javascript_include_tag 'supersized.3.2.6.min.js' %>
	<%= javascript_include_tag 'supersized.shutter.js' %>


	<!--
		Supersized - Fullscreen Slideshow jQuery Plugin
		Version : 3.2.6
		Site	: www.buildinternet.com/project/supersized
		
		Author	: Sam Dunn
		Company : One Mighty Roar (www.onemightyroar.com)
		License : MIT License / GPL License
	-->
		
		<script type="text/javascript">
			
			jQuery(function($){
				
				$.supersized({
				
					// Functionality
					slide_interval          :   5000,		// Length between transitions
					transition              :   1, 			// 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
					transition_speed		:	300,		// Speed of transition
															   
					// Components							
					slide_links				:	false,	// Individual links for each slide (Options: false, 'num', 'name', 'blank')
					thumb_links				:	1,			// Individual thumb links for each slide
					thumbnail_navigation    :   0,			// Thumbnail navigation
					slides 					:  	[			// Slideshow Images
												<%= render :partial => 'photo_slideshow', :collection => @photos %>
												]
					
				});
		    });
		    
		</script>
		
<% end %>
	
	<style type="text/css">
		ul#demo-block{ margin:0 15px 15px 15px; }
			ul#demo-block li{ margin:0 0 10px 0; padding:10px; display:inline; float:left; clear:both; color:#aaa; background:url('../../images/supersized/bg-black.png'); font:11px Helvetica, Arial, sans-serif; }
			ul#demo-block li a{ color:#eee; font-weight:bold; }
	</style>

<body>

	<!--Website Navigation-->
	<%= link_to '', photoset_path(@photoset), :id => 'back-button' %> 
	
	<!--Thumbnail Navigation-->
	<div id="prevthumb"></div>
	<div id="nextthumb"></div>
	
	<!--Arrow Navigation-->
	<a id="prevslide" class="load-item"></a>
	<a id="nextslide" class="load-item"></a>
	
	<div id="thumb-tray" class="load-item">
		<div id="thumb-back"></div>
		<div id="thumb-forward"></div>
	</div>
	
	<!--Control Bar-->
	<div id="controls-wrapper" class="load-item">
		<div id="controls">
			
			<a id="play-button"><img id="pauseplay" src="../../images/supersized/pause.png"/></a>
		
			<!--Slide counter-->
			<div id="slidecounter">
				<span class="slidenumber"></span> / <span class="totalslides"></span>
			</div>
			
			<!--Slide captions displayed here-->
			<div id="slidecaption"></div>
			
			<!--Thumb Tray button-->
			<a id="tray-button"><img id="tray-arrow" src="../../images/supersized/button-tray-up.png"/></a>

			<!--Navigation-->
			<ul id="slide-list"></ul>
			
			
		</div>
	</div>

</body>
</html>