config/routes.rb
Tripping::Application.routes.draw do
    
  resources :photosets, :only => [:index, :show] do
    member do
      get 'slideshow'
    end
  end

  namespace :admin do
    resources :photosets, :only => [:create, :destroy, :update] do
      collection do
        post 'save_order'
      end
    end
  end

  
  root :to => "pages#home"

  match "/admin/" => "admin#index", :as => :admin
  match "/friends/" => "photosets#friends"
  match "/about/" => "pages#about"
  match "/proxy/" => "pages#image_proxy"
end

app/views/admin/_header.html.erb
<div id="header">
	<a id="logo" href="/">Tripping</a>
	<ul id="menu">
		<li><%= link_to "Sets", :admin, :class => "sets" %></li>
		<li><%= link_to "Blog", "http://www.tumblr.com/blog/iamtripping" %></li>
	</ul>
</div>

app/views/admin/_not_imported_set.html.erb
<div class="thumbs">
	<%= image_tag( flickrurl_240(not_imported_set.primary), :alt => not_imported_set.title ) %>
	<h3><%= not_imported_set.title %></h3>
	<p class="info">Set ID: <%= not_imported_set.id %></br>
	<%= not_imported_set.photos %> fotos</p>
	<%= form_for [:admin, @new_photoset] do |f| %>
				                      <%= f.hidden_field :name, :value => not_imported_set.title %>
				                      <%= f.hidden_field :flickr_set_id, :value => not_imported_set.id %>
				                      <%= f.hidden_field :flickr_thumb_url, :value => flickrurl_240(not_imported_set.primary) %>
				                      <%= f.submit "Import" %>
	<% end %>
</div>

app/views/admin/_photoset.html.erb
<div class="thumbs" id="set_<%= photoset.id %>">
	<%= image_tag( photoset.flickr_thumb_url, :alt => photoset.name ) %>
	<h3><%= photoset.name %></h3>
	<p><%= link_to "Update", admin_photoset_path(photoset), :confirm => "Are you sure?", :method => :put %> /
	<%= link_to "Delete", admin_photoset_path(photoset), :confirm => "Are you sure?", :method => :delete %></p>
</div>

app/views/admin/index.html.erb
<% content_for :header do %>
	<%= javascript_include_tag 'admin.js' %>
    <%= stylesheet_link_tag 'admin.css' %>
<% end %>
<% content_for :body_class, 'admin sets' %>
<%= render 'header' %>

<% flash.each do |key, value| %>
  		<%= content_tag(:div, value, :class => "flash #{key}") %>
<% end %>

<div id="admin_actions">
</div>
	<div id="thumb_container" data-update-url="<%= save_order_admin_photosets_path %>">
		<h2>Sets:</h2>
		<% unless @photosets.empty? %>
			<%= render :partial => 'admin/photoset', :collection => @photosets %>
		<% else %>
			<p>No photosets to show.</p>
		<% end %>
	</div>
	<div id="thumb_container_notimported">
	    <% unless @not_imported_sets.empty? %>
		   <h2>Not imported sets:</h2>
	    	<%= render :partial => 'admin/not_imported_set', :collection => @not_imported_sets %>
	    <% end %>   
	</div> 
</div>